namespace Wyrdrasil.Core.Tool;

public enum RegistryActionType
{
    None,

    CreateTavernZone,
    CreateBedroomZone,
    CreateNavigationWaypoint,
    ConnectNavigationWaypoints,
    DeleteNavigationWaypoint,
    DeleteZone,

    CreateInnkeeperSlot,
    DesignateSeatFurniture,
    DesignateBedFurniture,
    DesignateCraftStationFurniture,
    DeleteSlot,
    DeleteDesignatedSeat,
    DeleteDesignatedBed,
    DeleteDesignatedCraftStation,

    RegisterNpc,
    AssignInnkeeperRole,
    AssignSeat,
    AssignBed,
    AssignCraftStation,
    ClearTargetInnkeeperSlotAssignment,
    ClearTargetSeatAssignment,
    ClearTargetBedAssignment,
    ClearTargetCraftStationAssignment,
    ForceAssignResident,
    DespawnTargetResident,
    RespawnAssignedResident,
    SpawnTestViking,

    InspectTargetNpcAi,
    EditTargetCraftStationAnchor,
    ProbeAssignedCraftStationOccupation,
    SimulateNoon,
    SimulateNight,
    ClearTimeSimulation,
    SpawnTestConstructionProject,
    DumpLatestConstructionProjectState,
    ForceCompleteLatestConstructionProject,
    ResetLatestConstructionProject,
    ToggleConstructionVerboseLogging,
    PlaceBlueprintInstantly,
    CaptureBlueprintFromTargetZone,
    AssignTargetResidentToLatestConstructionProject,
    AssignTargetCraftStationToConstructionProject,
    ClearTargetResidentConstructionAssignment,
    DeleteConstructionInTargetZone,
    FlushRegistryState
}
